# Generated by Django 3.1 on 2020-08-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_investment', models.IntegerField()),
                ('initial_year', models.IntegerField()),
                ('revenue_share_rate', models.IntegerField(default=1400)),
                ('project_size', models.IntegerField()),
                ('discount_rate', models.IntegerField(default=6)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.locality')),
            ],
        ),
    ]
