# Generated by Django 3.1 on 2020-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
