# Generated by Django 3.1 on 2021-01-08 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201211_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='scc_depreciation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.9, 0.9, 0.9, 0.9, 0.9, 0.8729, 0.847, 0.8196, 0.7906, 0.7598, 0.7271, 0.6925, 0.6568, 0.617, 0.5758, 0.5321, 0.4858, 0.4367, 0.3847, 0.3295, 0.2711, 0.2091, 0.1434, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1], size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scc_depreciation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.9, 0.9, 0.9, 0.9, 0.9, 0.8729, 0.847, 0.8196, 0.7906, 0.7598, 0.7271, 0.6925, 0.6568, 0.617, 0.5758, 0.5321, 0.4858, 0.4367, 0.3847, 0.3295, 0.2711, 0.2091, 0.1434, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1], size=None),
        ),
    ]
