# Generated by Django 3.1 on 2021-01-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
    ]
