# Generated by Django 3.1 on 2020-09-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20200830_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='revenue_share_rate',
        ),
        migrations.AddField(
            model_name='locality',
            name='discount_rate',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='locality',
            name='revenue_share_rate',
            field=models.IntegerField(default=1400),
        ),
    ]
