# Generated by Django 3.1 on 2021-01-13 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 18, 42, 11, 758467, tzinfo=utc)),
        ),
    ]
