# Generated by Django 3.1 on 2021-01-13 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210113_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 20, 46, 20, 773342, tzinfo=utc)),
        ),
    ]
