# Generated by Django 3.1 on 2020-09-17 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20200917_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='mt_tax_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=31),
        ),
    ]
