# Generated by Django 3.1 on 2020-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20200917_0948'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='simulation',
            constraint=models.UniqueConstraint(fields=('locality', 'initial_investment', 'initial_year', 'project_size'), name='unique_locality_simulation'),
        ),
    ]
