# Generated by Django 3.1 on 2021-01-18 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20210113_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 17, 55, 8, 424894, tzinfo=utc)),
        ),
    ]
