# Generated by Django 3.1 on 2021-02-23 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20210118_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='organization',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 14, 43, 15, 373940, tzinfo=utc)),
        ),
    ]
