# Generated by Django 3.1.7 on 2021-06-02 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20210306_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='revenue_share_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='revenue_share_rate',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 15, 33, 48, 753225, tzinfo=utc)),
        ),
    ]
