# Generated by Django 3.1 on 2020-09-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_locality_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locality',
            old_name='real_propery_rate',
            new_name='real_property_rate',
        ),
    ]
