# Generated by Django 3.1.7 on 2021-06-03 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20210603_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='revenue_share_rate',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 18, 3, 5, 205492, tzinfo=utc)),
        ),
    ]
