# Generated by Django 3.1 on 2020-10-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20200930_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='mt_tax_rate',
        ),
    ]
