# Generated by Django 3.1 on 2020-10-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_remove_locality_mt_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='mt_tax_rate',
            field=models.FloatField(default=0),
        ),
    ]
