# Generated by Django 3.1 on 2020-10-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_locality_mt_tax_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='inside_fence_acerage',
            new_name='inside_fence_acreage',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='total_acerage',
            new_name='total_acreage',
        ),
    ]
