# Generated by Django 6.0.2 on 2026-02-15 19:19

import django.contrib.postgres.fields
import django.utils.timezone
import models.models
from django.db import migrations, models as django_models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='id',
            field=django_models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=django_models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=django_models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='assessment_ratio',
            field=django_models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='locality',
            name='id',
            field=django_models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='local_depreciation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_models.FloatField(), blank=True, null=True, size=35),
        ),
        migrations.AlterField(
            model_name='locality',
            name='scc_depreciation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_models.FloatField(), default=models.models.get_scc_depreciation),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=django_models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='adj_gross_income',
            field=django_models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='assessment_ratio',
            field=django_models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=django_models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='local_depreciation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_models.FloatField(), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='revenue_share_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_models.FloatField(), default=models.models.get_default_revenue_share_rate),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scc_depreciation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_models.FloatField(), default=models.models.get_scc_depreciation),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='taxable_retail_sales',
            field=django_models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
