# Generated by Django 6.0.2 on 2026-02-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_alter_calculations_id_alter_feedback_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locality_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
