# Generated by Django 3.1 on 2020-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_auto_20201001_2026'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='simulation',
            name='unique_locality_simulation',
        ),
        migrations.AddConstraint(
            model_name='simulation',
            constraint=models.UniqueConstraint(fields=('locality', 'initial_investment', 'initial_year', 'project_size', 'total_acreage', 'inside_fence_acreage', 'baseline_land_value', 'inside_fence_land_value'), name='unique_locality_simulation'),
        ),
    ]
