# Generated by Django 3.1 on 2020-10-11 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_auto_20201003_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='local_deprecition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None),
        ),
    ]
