# Generated by Django 3.1 on 2020-10-11 17:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_locality_local_deprecition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='local_deprecition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, null=True, size=None),
        ),
    ]
