# Generated by Django 3.1 on 2020-10-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_auto_20201011_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='years_between_assesment',
            field=models.IntegerField(default=5),
        ),
    ]
