# Generated by Django 3.1 on 2020-10-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_auto_20201013_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locality',
            old_name='assesment_ratio',
            new_name='assessment_ratio',
        ),
    ]
