# Generated by Django 3.1 on 2020-11-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0034_locality_use_composite_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='use_composite_index',
            field=models.TextField(default='on'),
        ),
    ]
