# Generated by Django 3.1 on 2020-08-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200820_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='initial_year',
            field=models.IntegerField(),
        ),
    ]
