# Generated by Django 3.1 on 2020-08-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20200821_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='initial_investment',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='initial_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='project_size',
            field=models.IntegerField(default=100),
        ),
    ]
