# Generated by Django 3.1 on 2020-09-17 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20200910_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='mt_tax_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=30),
        ),
    ]
