# Generated by Django 3.1 on 2020-09-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20200917_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='real_propery_rate',
            field=models.FloatField(default=0),
        ),
    ]
