# Generated by Django 3.1 on 2020-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20200930_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='population',
        ),
        migrations.AlterField(
            model_name='locality',
            name='adj_gross_income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locality',
            name='baseline_true_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locality',
            name='taxable_retail_sales',
            field=models.BigIntegerField(default=0),
        ),
    ]
