# Generated by Django 3.1 on 2020-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20200930_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
