# Generated by Django 3.1 on 2020-10-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_auto_20201011_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locality',
            old_name='local_deprecition',
            new_name='local_depreciation',
        ),
    ]
