# Generated by Django 3.1 on 2020-10-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_locality_years_between_assesment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locality',
            old_name='years_between_assesment',
            new_name='years_between_assessment',
        ),
    ]
