# Generated by Django 3.1 on 2020-10-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_auto_20201014_1022'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='simulation',
            name='unique_locality_simulation',
        ),
        migrations.AddField(
            model_name='simulation',
            name='outside_fence_land_value',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddConstraint(
            model_name='simulation',
            constraint=models.UniqueConstraint(fields=('locality', 'initial_investment', 'initial_year', 'project_size', 'total_acreage', 'inside_fence_acreage', 'baseline_land_value', 'inside_fence_land_value', 'outside_fence_land_value', 'dominion_or_apco'), name='unique_locality_simulation'),
        ),
    ]
