# Generated by Django 3.1 on 2020-10-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_locality_scc_depreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='project_length',
            field=models.IntegerField(default=30),
        ),
    ]
