# Generated by Django 3.1 on 2020-11-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_auto_20201024_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='use_composite_index',
            field=models.BooleanField(default=True),
        ),
    ]
