# Generated by Django 3.1 on 2020-11-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0035_auto_20201105_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='use_composite_index',
            field=models.BooleanField(default=True),
        ),
    ]
