# Generated by Django 3.1 on 2020-11-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0038_auto_20201110_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='locality',
        ),
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.userprofile'),
        ),
    ]
