# Generated by Django 3.1 on 2020-11-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0040_auto_20201111_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
