"""
Django settings for SolarTax project.

Generated by 'django-admin startproject' using Django 3.1.
Updated to Django 6.02 in 2026.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/

"""
from django.conf import settings
import django_heroku
import os
import dj_database_url

import psycopg2
# from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: Keep the secret key used in production secret!
if os.path.exists('hiddenVars/secret_key.txt'):
    with open('hiddenVars/secret_key.txt') as f:
        SECRET_KEY = f.read().strip()
else:
    SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: Don't run with debug turned on in production!

if os.path.exists('hiddenVars'):
    DEBUG = True
    ALLOWED_HOSTS = ['https://solar-tax-webapp-dev.azurewebsites.net','127.0.0.1', 'localhost']
else:
    DEBUG = True
    ALLOWED_HOSTS = ['solar-tax-webapp.azurewebsites.net', 'https://solar-tax-webapp-dev.azurewebsites.net', 'localhost', '127.0.0.1']
# ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'models.apps.ModelsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.postgres',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels',
    'channels_redis',
    'crispy_forms',
    'crispy_bootstrap4', 
]

MIDDLEWARE = [
    'models.middleware.MaintenanceModeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SolarTax.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':[
                'models.templatetags.custom_tags',
            ]
        },
    },
]

# WSGI_APPLICATION = 'SolarTax.wsgi.application'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


if os.path.exists('hiddenVars/azure_name.txt') :
    with open('hiddenVars/azure_name.txt') as f:
        NAME = str(f.read().strip())
else:
    NAME = os.environ['NAME']  

if os.path.exists('hiddenVars/azure_user.txt'):
    with open('hiddenVars/azure_user.txt') as f:
        USER = str(f.read().strip())
else:
    USER = os.environ['USER']   

if os.path.exists('hiddenVars/azure_password.txt'):
    with open('hiddenVars/azure_password.txt') as f:
        PASSWORD = str(f.read().strip())
else:
    PASSWORD = os.environ['PASSWORD']    

if os.path.exists('hiddenVars/azure_host.txt'):
    with open('hiddenVars/azure_host.txt') as f:
        HOST = str(f.read().strip())
else:
    HOST = os.environ['HOST'] 

if os.path.exists('hiddenVars/azure_port.txt'):
    with open('hiddenVars/azure_port.txt') as f:
        PORT = str(f.read().strip())
else:
    PORT = os.environ['PORT'] 


DATABASES = {
     'default': { 
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': NAME,
         'USER': USER,
         'PASSWORD': PASSWORD,
         'HOST': HOST,
         'PORT': PORT,
     }
 }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ASGI_APPLICATION = 'SolarTax.routing.applications'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG':{
            'hosts': [{'localhost', '8000'}],
        }
    }
}

STATIC_FINDERS ={
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.plotly.dash.finders.DashAssestFinder',
    'django.plotly.dash.finders.DashComponentFinder'
}

PLOTLY_COMPONENTS=[
    'dash_core_components',
    'dash_html_components',
    'dash_renderer',
    'dpd_components'
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = 'localityName'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'VaSolar@virginia.edu'
EMAIL_HOST_PASSWORD = 'hdwprsfxxnjedphc'
# if os.path.exists('hiddenVars/email.txt'):
#     with open('hiddenVars/email.txt') as f:
#         EMAIL_HOST_USER = str(f.read().strip())
# else:
#     EMAIL_HOST_USER = str(os.environ['EMAIL_HOST_USER'])

# if os.path.exists('hiddenVars/email_password.txt'):
#     with open('hiddenVars/email_password.txt') as f:
#         EMAIL_HOST_PASSWORD = str(f.read().strip())
# else:
#     EMAIL_HOST_PASSWORD= str(os.environ['EMAIL_HOST_PASSWORD'])
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
'''
try:
    # Configure Django App for Heroku.
    import django_heroku
    django_heroku.settings(locals())
except ImportError:
    found = False
'''
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"  
CRISPY_TEMPLATE_PACK = 'bootstrap4' 

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGIN = ['https://solar-tax-webapp.azurewebsites.net', 'https://solar-tax-webapp-dev.azurewebsites.net','localhost', '127.0.0.1']

MAINTENANCE_MODE = False

#***********************************************
# PARAMETER VALUES. -- make sure to document where these are used
#***********************************************
''' Used in views.py function perform_calculations
   state_true_value = [1170092111098.94 for i in range(project_length)]
    state_adj_gross_income = 269067675604.708
    state_taxable_retail_sales = 100207273998.18
    state_adm = 1239781.3
    state_population = 8382993
    mt_stepdown = [.8, .8, .8, .8, .8, .7, .7, .7, .7, .7, .6]
'''
STATE_TRUE_VALUE = 1170092111098.94   #need to document this value
STATE_ADJ_GROSS_INCOME = 269067675604.708
STATE_TAXABLE_RETAIL_SALES = 100207273998.18
STATE_ADM = 1239781.3
STATE_POPULATION = 8382993
MT_STEPDOWN = [.8, .8, .8, .8, .8, .7, .7, .7, .7, .7, .6]

MAX_RS = [1400, 1540, 1694, 1863, 2050, 2255, 2480, 2728, 3001]
RS_YEARS = [2021, 2026, 2031, 2036, 2041, 2046, 2051, 2056, 2061]
# This revenue share rate schedule is used in the revenue share update function in views.py and should be updated if that function is updated. It is also the default value for the revenue share rate field in the UserProfile model, and should be updated if that default value is updated.
# used in revenue_calculations.get_adjusted_revenue_share_rate
# appears to be identical to MAX_RS
REVENUE_SHARE_RATE = [1400, 1540, 1694, 1863, 2050, 2255, 2480, 2728, 3001]
DEFAULT_REVENUE_SHARE_RATE = [1400, 1540, 1694, 1863, 2050, 2255, 2480, 2728, 3001]
# This value appears in views.revenueShareUpdate document it!!
REVENUE_SHARE_UPDATE_YEARS = [2021, 2026, 2031, 2036, 2041, 2046, 2051, 2056, 2061]

SCC_DEPRECIATION_RATES = [0.9, 0.9, 0.9, 0.9, 0.9, 0.8729, 0.8470, 0.8196, 0.7906, 0.7598, 0.7271, 0.6925, 0.6568, 0.6170, 0.5758, 0.5321, 0.4858, 0.4367, 0.3847, 0.3295, 0.2711, 0.2091, 0.1434]

SOLTAX_EMAIL_ADDRESS = EMAIL_HOST_USER

ACRE_LIMIT_25 = 25
ACRE_LIMIT_50 = 50
ACRE_LIMIT_150 = 150

MAX_PROJECT_LENGTH = 35
MAX_DEPRECIATION_SCHEDULE_LENGTH = MAX_PROJECT_LENGTH
DEFAULT_PROJECT_LENGTH = 30
# Used in the true value calculations in revenue_calculations.new_land_value. It is currently set to 1.2%, but should be revisited periodically.
ANNUAL_PROPERTY_APPRECIATION_RATE = 0.012   # 1.2% annual appreciation rate

# Composite index parameters - used in views.py compositeIndexUpdate function and in the composite index calculation in revenue_calculations.composite_index
COMPOSITE_INDEX_BASE_YEAR = 2017
COMPOSITE_INDEX_BASE_VALUE = 100
# 50% true value, 40% income, 10% sales - these weights are used in the composite index calculation in revenue_calculations.composite_index and should be updated if the composite index calculation is updated
COMPOSITE_INDEX_WEIGHTS = {
    'true_value': 0.5,
    'adj_gross_income': 0.4,
    'taxable_retail_sales': 0.1
}
LOCAL_COMPOSITE_INDEX_SHARES = {
    'adm_share': 2/3,
    'population_share': 1/3
}
LOCAL_COMPOSITE_INDEX_SCALE_FACTOR = 0.45   # This factor is used to scale the local composite index in revenue_calculations.composite_index.
# Base year for discounting. Present value will be expressed in terms of dollars in this year. 
# Used in revenue_calculations.discount_cash_flows and should be updated if that function is updated.
DISCOUNTING_BASE_YEAR = 2020
DEFAULT_DISCOUNT_RATE = 6
# The earliest initial year that can be entered in the user input form. 
# This is used in the form validation in forms.py and should be updated if that validation is updated.
EARLIEST_INITIAL_YEAR = 2025
LATEST_INITIAL_YEAR = 2050
DEFAULT_INITIAL_YEAR = 2021

DEFAULT_YEARS_BETWEEN_ASSESSMENTS = 5


PROPERTY_APPRECIATION_SCHEDULE  = []
for i in range(MAX_PROJECT_LENGTH):
    PROPERTY_APPRECIATION_SCHEDULE.append((1 + ANNUAL_PROPERTY_APPRECIATION_RATE) ** (i + 1))
