import math
import json
from django.conf import settings


def depreciation_ext(depreciation_schedule):
    """
    Takes in schedule of effective rates
    Returns extended list with final effective rate to be available for calculations out to 35 years
    Does NOT modify original list
    """
    # Handle string representation of list (from database)
    
    if isinstance(depreciation_schedule, str):
        try:
            depreciation_schedule = [float(x) for x in depreciation_schedule.strip('{}').split(',')]
        except (ValueError, TypeError):
            depreciation_schedule = []
    extended = depreciation_schedule.copy() if depreciation_schedule else []
    if not extended:
        return extended
    
    last_rate = extended[-1]
    # hardcoded value alert - 35 year extension for depreciation schedule, should be sufficient for all current projects modeled but may want to make more dynamic in the future
    while len(extended) < settings.MAX_DEPRECIATION_SCHEDULE_LENGTH:
        extended.append(last_rate)
    return extended


def effective_rate_ext(effective_rate_list, project_length):
    """
    Takes in schedule of effective rates
    Returns extended list with final effective rate available for project length
    Does NOT modify original list
    """
       # Handle string representation of list (from database)
    if isinstance(effective_rate_list, str):
        try:
            effective_rate_list = json.loads(effective_rate_list)
        except (json.JSONDecodeError, TypeError):
            effective_rate_list = []
    extended = effective_rate_list.copy() if effective_rate_list else []
    if not extended:
        return extended
    
    last_rate = extended[-1]
    while len(extended) <= project_length:
        extended.append(last_rate)
    
    return extended


###############################################################################
# FUNCTIONS TO GET TOTAL MT REVENUE GENERATED BY SOLAR FACILITY
###############################################################################

# This code is never used.
def get_mt_exemption(size_mw, mt_exemption):
    """
    Get the exemption rate for the project. 
    If above 150 MW, no exemptions applied. Otherwise use M&T stepdown exemption rate
    Calculations moved to views.py to handle real estate rate threshold logic.
    """
    # ACRE_LIMIT_150 - 150 MW exemption threshold
    if size_mw > settings.ACRE_LIMIT_150:
        #print(f"No M&T exemption applied for project size {size_mw} MW")
        return 0
    else:
        #print(f"Applying M&T exemption rate: {mt_exemption}% for project size {size_mw} MW")
        return mt_exemption

# This code is never used. Calculations moved to views.py to handle real estate rate threshold logic.
def get_mt_tax_rate(size_mw, mt_tax_rate, real_estate_rate):
    """
    Get the M&T tax rate for the project. 
    If above 25 MW use real estate rate, otherwise use mt_tax_rate
    """
    # ACRE_LIMIT_25 - 25 MW threshold for real estate rate
    if size_mw > settings.ACRE_LIMIT_25:
        #print(f"Using real estate rate: {real_estate_rate}% for project size {size_mw} MW")
        return real_estate_rate
    else:
        return mt_tax_rate


###############################################################################
# Calculations for Valuation of Proposed Solar Facility
###############################################################################


def solar_facility_valuation(year, investment, mt_exemption, depreciation_schedule, 
                             assessment_ratio, project_length):
    """Calculate solar facility valuation over project lifetime"""
    print(f"solar_facility_valuation: assessment_ratio {assessment_ratio}, investment {investment}, mt_exemption {mt_exemption}\n")
    valuation = []
    for i in range(project_length):
        after_exemption = investment * (1 - mt_exemption[i])
        after_depreciation = after_exemption * depreciation_schedule[i]
        assessed_facility_valuation = after_depreciation * assessment_ratio
        valuation.append(round(assessed_facility_valuation))
    return valuation


###############################################################################
# Calculations for increase in Land Value
###############################################################################


def current_land_value(total_acreage, baseline_value, starting_year, project_length, 
                      years_between_assessment,property_appreciation_schedule):
    """Calculate land value for each year in project_length with annual appreciation at ANNUAL_PROPERTY_APPRECIATION_RATE% """
    baseline = []
    total_acreage_value = total_acreage * baseline_value
    for i in range(project_length):
        if i % years_between_assessment == 0:
            baseline.append(round(total_acreage_value * property_appreciation_schedule[i]))
        else:
            baseline.append(baseline[i - 1])
    return baseline


def new_land_value(total_acreage, inside_acreage, outside_acreage, inside_fence_value, 
                  outside_fence_value, starting_year, project_length, years_between_assessment,
                  property_appreciation_schedule):
    """Calculate new land value with solar project"""
    total = []
    inside_fence_total_value = inside_acreage * inside_fence_value
    outside_fence_total_value = outside_acreage * outside_fence_value
    for i in range(project_length):
        if i % years_between_assessment == 0:
            # ANNUAL_PROPERTY_APPRECIATION_RATE - 1.2% annual property appreciation rate
            inside = inside_fence_total_value * property_appreciation_schedule[i]
            outside = outside_fence_total_value * property_appreciation_schedule[i]
            total.append(round(inside + outside))
        else:
            total.append(total[i - 1])
    return total


def increase_in_land_value(current_land_value, new_land_value, assessment_ratio):
    """Calculate difference between new and current land values"""
    difference = []
    for i in range(len(current_land_value)):
        difference.append(round((new_land_value[i] - current_land_value[i]) * assessment_ratio))
    return difference


###############################################################################
# Gross Revenue from Project Calculations
###############################################################################


def increased_county_gross_revenue_from_project(solar_valuation_list, applied_mt_tax_rate, 
                                               increase_in_land_value, applied_real_estate_rate):
    """Calculate increase in gross revenue from solar project and land"""
    gross_revenue_increase = []
    for i in range(len(solar_valuation_list)):
        # The tax rates are defined as rates per $100 of value, so we divide by 100 in the calculations below. 
        # This division is being moved to views.performCalculations to avoid having to remember to do this in 
        # every function that uses the tax rates, but we should consider a more robust way to handle this in the 
        # future to avoid confusion.
        increase_from_solar = (solar_valuation_list[i] * applied_mt_tax_rate[i])
        increase_from_land = (increase_in_land_value[i] * applied_real_estate_rate)
        gross_revenue_increase.append(round(increase_from_solar + increase_from_land))
    return gross_revenue_increase


def current_land_revenue(current_land_value, applied_real_estate_rate):
    """Calculate current revenue from existing land"""
    current_revenue = []
    for i in range(len(current_land_value)):
        # The applied rate is in terms of tax rate per $100. Dividing by 100 was moved to views.performCalculations.
        current_revenue.append(round(current_land_value[i] * (applied_real_estate_rate)))
    return current_revenue


def total_gross_revenue_mt(current_revenue, gross_revenue_increase):
    """Calculate total gross M&T revenue"""
    total_revenue = []
    for i in range(len(current_revenue)):
        total_revenue.append(current_revenue[i] + gross_revenue_increase[i])
    return total_revenue


###############################################################################
# FUNCTIONS TO GET TOTAL TAX AVAILABLE TO LOCALITIES FROM MT TAX
###############################################################################


def net_total_revenue_from_project(gross_revenue_project, increase_in_local_contribution):
    """Calculate net revenue after education contributions"""
    net_total_revenue = []
    for i in range(len(gross_revenue_project)):
        net_total_revenue.append(round(gross_revenue_project[i] - increase_in_local_contribution[i]))
    return net_total_revenue


def increase_in_local_contribution(pv_required_education_contribution, 
                                  baseline_required_education_contribution):
    """Calculate increase in education contribution"""
    increase_contribution = []
    for i in range(len(pv_required_education_contribution)):
        increase_contribution.append(
            pv_required_education_contribution[i] - baseline_required_education_contribution[i]
        )
    return increase_contribution


def pv_required_education_contribution(locality_education_budget, budget_escalator, 
                                      pv_composite_index):
    """Calculate project-value required education contribution"""
    pv_education_contribution = []
    for i in range(len(pv_composite_index)):
        # The budget escalator value in the database is divided by 100 in views.performCalculations 
        # before being passed to this function, so we do not divide by 100 in the calculation below.
        contribution = locality_education_budget * ((1 + budget_escalator) ** i) * pv_composite_index[i]
        pv_education_contribution.append(contribution)
    return pv_education_contribution


def baseline_required_education_contribution(locality_education_budget, budget_escalator, 
                                           baseline_composite_index):
    """Calculate baseline required education contribution"""
    baseline_education_contribution = []
    for i in range(len(baseline_composite_index)):
        contribution = locality_education_budget * ((1 + budget_escalator) ** i) * baseline_composite_index[i]
        baseline_education_contribution.append(contribution)
    return baseline_education_contribution


###############################################################################
# COMPOSITE INDEX FUNCTIONS
###############################################################################


def composite_index(adm_composite_index, per_capita_composite_index):
    """Calculate final composite index (2/3 ADM, 1/3 per capita, scaled by 0.45)
     Document the calculations."""
    final_pv_composite_index = []
    for i in range(len(adm_composite_index)):
        # hardcoded values alert
        local_composite_index = ((settings.LOCAL_COMPOSITE_INDEX_SHARES['adm_share'] * adm_composite_index[i]) +
        (settings.LOCAL_COMPOSITE_INDEX_SHARES['population_share'] * per_capita_composite_index[i]))
        value = settings.LOCAL_COMPOSITE_INDEX_SCALE_FACTOR * local_composite_index
        # Why the scaling time 10,000? 
        # Suggested reason: This is to preserve 4 decimal places in the final composite index while avoiding floating point precision issues that 
        # can arise with very small decimal numbers. By multiplying by 10,000 before truncating, we can keep 4 decimal places of precision without running into issues where the number becomes too small to represent accurately in Python's floating point arithmetic. After truncating, we divide by 10,000 to return to the original scale.
        factor = 10.0 ** 4
        final_pv_composite_index.append(math.trunc((value * factor)) / factor)
    return final_pv_composite_index


def adm_composite_index(true_values_adm, gross_income_adm, retail_sales_adm):
    """Calculate ADM composite index (50% true value, 40% income, 10% sales)"""
    #print(f'Calculating ADM composite index:\n')
    #print(f'True values (ADM): {true_values_adm}\n')
    #print(f'Gross income (ADM): {gross_income_adm}\n')
    #print(f'Retail sales (ADM): {retail_sales_adm}\n')
    final_adm_composite_index = []
    for i in range(len(true_values_adm)):
        adm_value = (settings.COMPOSITE_INDEX_WEIGHTS['true_value'] * true_values_adm[i] + 
                    settings.COMPOSITE_INDEX_WEIGHTS['adj_gross_income'] * gross_income_adm[i] + 
                    settings.COMPOSITE_INDEX_WEIGHTS['taxable_retail_sales'] * retail_sales_adm[i])
        final_adm_composite_index.append(adm_value)
        #print(f'ADM value for year {i}: {adm_value}')

    return final_adm_composite_index


def per_capita_composite_index(true_values_per_capita, gross_income_per_capita, 
                               retail_sales_per_capita):
    """Calculate per capita composite index (50% true value, 40% income, 10% sales)"""
    final_per_capita_composite_index = []
    for i in range(len(true_values_per_capita)):
        # hardcoded values alert
        per_capita_value = (settings.COMPOSITE_INDEX_WEIGHTS['true_value'] * true_values_per_capita[i] + 
                          settings.COMPOSITE_INDEX_WEIGHTS['adj_gross_income'] * gross_income_per_capita[i] + 
                          settings.COMPOSITE_INDEX_WEIGHTS['taxable_retail_sales'] * retail_sales_per_capita[i])
        final_per_capita_composite_index.append(per_capita_value)
    return final_per_capita_composite_index


###############################################################################
# TRUE VALUE CALCULATIONS
###############################################################################


def get_true_values_adm(local_true_values, divisional_adm, statewide_total_true_values, 
                       total_state_adm):
    """Calculate true values indexed by ADM"""
    final_true_values = []
    for i in range(len(local_true_values)):
        if divisional_adm == 0 or total_state_adm == 0:
            final_true_values.append(0)
            continue
        numerator = local_true_values[i] / divisional_adm
        denominator = statewide_total_true_values[i] / total_state_adm
        if denominator == 0:
            final_true_values.append(0)
        else:
            final_true_values.append(numerator / denominator)
    return final_true_values


def get_true_values_per_capita(local_true_values, local_pop, statewide_total_true_values, 
                              state_pop):
    """Calculate true values per capita"""
    final_true_values = []
    for i in range(len(local_true_values)):
        if local_pop == 0 or state_pop == 0:
            final_true_values.append(0)
            continue
        numerator = local_true_values[i] / local_pop
        denominator = statewide_total_true_values[i] / state_pop
        if denominator == 0:
            final_true_values.append(0)
        else:
            final_true_values.append(numerator / denominator)
    return final_true_values


def get_baseline_true_values_adm(baseline_true_values, divisional_adm, 
                                baseline_state_true_values, total_state_adm):
    """Calculate baseline true values indexed by ADM"""
    final_true_values = []
    for i in range(len(baseline_state_true_values)):
        if divisional_adm == 0 or total_state_adm == 0:
            final_true_values.append(0)
            continue
        numerator = baseline_true_values / divisional_adm
        denominator = baseline_state_true_values[i] / total_state_adm
        if denominator == 0:
            final_true_values.append(0)
        else:
            final_true_values.append(numerator / denominator)
    return final_true_values


def get_baseline_true_values_per_capita(baseline_true_values, local_pop, 
                                       baseline_state_true_values, state_pop):
    """Calculate baseline true values per capita"""
    final_true_values = []
    for i in range(len(baseline_state_true_values)):
        if local_pop == 0 or state_pop == 0:
            final_true_values.append(0)
            continue
        numerator = baseline_true_values / local_pop
        denominator = baseline_state_true_values[i] / state_pop
        if denominator == 0:
            final_true_values.append(0)
        else:
            final_true_values.append(numerator / denominator)
    return final_true_values


def local_true_values(baseline_true_value, increase_in_taxable_property):
    """Calculate local true values with project"""
    final_local_true_values = []
    for i in range(len(increase_in_taxable_property)):
        final_local_true_values.append(baseline_true_value + increase_in_taxable_property[i])
    return final_local_true_values


def state_total_true_values(baseline_state_true_value, increase_in_taxable_property):
    """Calculate state total true values"""
    final_state_true_values = []
    for i in range(len(increase_in_taxable_property)):
        final_state_true_values.append(
            baseline_state_true_value[i] + increase_in_taxable_property[i]
        )
    return final_state_true_values


def increase_in_taxable_property(increase_in_land_value, solar_facility_valuation):
    """Calculate increase in taxable property from land and solar"""
    inc_taxable_property = [
        increase_in_land_value[i] + solar_facility_valuation[i] 
        for i in range(len(solar_facility_valuation))
    ]
    return inc_taxable_property


###############################################################################
# GROSS INCOME CALCULATIONS
###############################################################################


def get_gross_income_adm(adj_gross_income, divisional_adm, statewide_gross_income, 
                        total_state_adm, project_length):
    """Calculate gross income indexed by ADM"""
    final_gross_income = []
    for i in range(project_length):
        if divisional_adm == 0 or total_state_adm == 0 or statewide_gross_income == 0   or adj_gross_income == 0:
            final_gross_income.append(0)
            continue
        else:
            numerator = adj_gross_income / divisional_adm
            denominator = statewide_gross_income / total_state_adm
            final_gross_income.append(numerator / denominator)
    return final_gross_income


def get_gross_income_per_capita(adj_gross_income, local_pop, statewide_gross_income, 
                               state_pop, project_length):
    """Calculate gross income per capita"""
    final_gross_income = []
    for i in range(project_length):
        if local_pop == 0 or state_pop == 0 or statewide_gross_income == 0   or adj_gross_income == 0:
            final_gross_income.append(0)
            continue
        else:
            numerator = adj_gross_income / local_pop
            denominator = statewide_gross_income / state_pop
            final_gross_income.append(numerator / denominator)
    return final_gross_income


###############################################################################
# RETAIL SALES CALCULATIONS
###############################################################################


def get_retail_sales_adm(local_taxable_retail_sales, divisional_adm, 
                        state_taxable_retail_sales, total_state_adm, project_length):
    """Calculate retail sales indexed by ADM"""
    final_retail_sales = []
    for i in range(project_length):
        if divisional_adm == 0 or total_state_adm == 0 or state_taxable_retail_sales == 0 or local_taxable_retail_sales == 0:
            final_retail_sales.append(0)
            continue
        else:
            numerator = local_taxable_retail_sales / divisional_adm
            denominator = state_taxable_retail_sales / total_state_adm
            final_retail_sales.append(numerator / denominator)
    return final_retail_sales


def get_retail_sales_per_capita(local_taxable_retail_sales, local_pop, 
                               state_taxable_retail_sales, state_pop, project_length):
    """Calculate retail sales per capita"""
    final_retail_sales = []
    for i in range(project_length):
        if local_pop == 0 or state_pop == 0 or local_taxable_retail_sales == 0 or state_taxable_retail_sales == 0:
            final_retail_sales.append(0)
            continue
        else:
            numerator = local_taxable_retail_sales / local_pop
            denominator = state_taxable_retail_sales / state_pop
            final_retail_sales.append(numerator / denominator)
    return final_retail_sales


###############################################################################
# REVENUE SHARE CALCULATIONS
###############################################################################


def get_adjusted_revenue_share_rate(initial_year, project_length, revenue_share_rate):
    """
    Get revenue share rate for each year of the project.
    Handles projects starting before or after 2021, and prevents index errors.
    """
    adjusted_rs_rate = []
    
    if not revenue_share_rate:
        # Default rates if none provided
        revenue_share_rate = settings.REVENUE_SHARE_RATE
    
    # hardcoded value alert
    if initial_year >= 2021:
        for i in range(initial_year, initial_year + project_length):
            # Calculate index with bounds checking
            index = (i - 2021) // 5
            index = min(index, len(revenue_share_rate) - 1)  # Prevent index error
            adjusted_rs_rate.append(revenue_share_rate[index])
    else:
        # For projects starting before 2021, use the earliest rate
        adjusted_rs_rate = [revenue_share_rate[0] for _ in range(project_length)]
    
    return adjusted_rs_rate


def total_cashflow_rs(revenue_share_rate, megawatts, year, project_length):
    """
    Calculate revenue share cashflow
    :revenue_share_rate: array of revenue rates
    :megawatts: Size of solar project
    :year: Starting year of the solar project
    :return: List of revenue share revenue generated during each year, nominal $
    """
    cashflow_rev = []
    for i in range(project_length):
        cashflow_rev.append(revenue_share_rate[i] * megawatts)
    return cashflow_rev


def total_adj_rev(cas, discount_rate, initial_year):
    """
    Calculate present value of revenue stream
    :cas: List of revenue generated during each year, nominal $
    :discount_rate: rate at which revenue values will be discounted
    :initial_year: Starting year of project
    :return: List of revenue generated during each year in present value
    """
    tot = []
    for i in range(len(cas)):
        if discount_rate == 0:
            tot.append(cas[i])
        else:
            tot.append(cas[i] / ((1 + discount_rate) ** (i + (initial_year - settings.DISCOUNTING_BASE_YEAR))))
    return tot


def apply_assessment_cycle(values, years_between_assessment):
    """
    Apply assessment cycle to values.
    Values are recalculated at assessment intervals, held constant between.
    """
    if not values:
        return []
    
    adjusted_values = []
    for i in range(len(values)):
        if i % years_between_assessment == 0:
            adjusted_values.append(values[i])
        else:
            adjusted_values.append(adjusted_values[i - 1])
    
    return adjusted_values